# Generated by Django 4.0.4 on 2022-07-07 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminuser',
            old_name='password1',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='adminuser',
            old_name='password2',
            new_name='re_password',
        ),
        migrations.AlterModelTable(
            name='adminuser',
            table='AdminUser',
        ),
    ]
