# Generated by Django 4.0.4 on 2022-07-11 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0002_rename_password1_adminuser_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('app_link', models.URLField(max_length=300)),
                ('app_category', models.CharField(choices=[('Entertainment', 'Entertainment'), ('Games', 'Games'), ('Finance', 'Finance'), ('Health', 'Health & Wellness')], max_length=255)),
                ('app_subcategory', models.CharField(choices=[('Social Media', 'Socical Media'), ('OTT', 'OTT'), ('Action', 'Action'), ('Adventure', 'Adventure'), ('Acrade', 'Acrade'), ('UPI', 'UPI'), ('Investments', 'Investments'), ('Fitness Tracking', 'Fitness Tracking')], max_length=255)),
                ('points', models.PositiveIntegerField()),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apps.adminuser')),
            ],
        ),
    ]
