# Generated by Django 4.0.4 on 2022-07-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0003_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='app_image',
            field=models.ImageField(default=None, upload_to='app_icons/'),
        ),
    ]
