# Generated by Django 4.0.4 on 2022-07-11 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0004_apps_app_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='admin_user',
            field=models.ForeignKey(default='Anonymous', on_delete=django.db.models.deletion.CASCADE, to='Apps.adminuser'),
        ),
    ]
