# Generated by Django 4.0.4 on 2022-08-24 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Apps', '0005_alter_apps_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='admin_user',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Apps.adminuser'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='app_category',
            field=models.CharField(choices=[('', 'App Category'), ('E-Commerce', 'E-Commerce'), ('Entertainment', 'Entertainment'), ('Games', 'Games'), ('Finance', 'Finance'), ('Health', 'Health & Wellness'), ('Jobs & Business', 'Jobs & Business'), ('Education', 'Education')], max_length=255),
        ),
        migrations.AlterField(
            model_name='apps',
            name='app_link',
            field=models.URLField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='apps',
            name='app_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='apps',
            name='app_subcategory',
            field=models.CharField(choices=[('', 'App Subcategory'), ('Shopping', 'Shopping'), ('Social Media', 'Socical Media'), ('Networking', 'Networking'), ('OTT', 'OTT'), ('Action', 'Action'), ('Adventure', 'Adventure'), ('Acrade', 'Acrade'), ('Role Playing', 'Role Playing'), ('UPI', 'UPI'), ('Investments', 'Investments'), ('Fitness Tracking', 'Fitness Tracking')], max_length=255),
        ),
        migrations.CreateModel(
            name='AppsDownloaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_ss', models.ImageField(upload_to='app screenshots')),
                ('points_earned', models.PositiveIntegerField(editable=False)),
                ('app', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='appsdownloaded', to='Apps.apps')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='appsdownloaded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
