# Generated by Django 4.0.4 on 2022-09-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0007_adminuser_name_alter_apps_app_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
